# -*- coding: utf-8 -*-
"""squareroot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EVAzxDRf-iW0FdyKniLSpLEIM249q5Kd
"""

def sqroot(x):
  return x**.5